- name: Provision Debian Pi-hole server
  hosts: dev
  become: true
  vars_files:
    - group_vars/vault.yml
  roles:
    - role: common
    - role: firewall
    - role: log2ram
    - role: docker
    - role: pihole
