- name: Basic server setup
  hosts: homelab
  become: true
  vars_files:
    - group_vars/vault.yml
  roles:
    - role: common
    - role: firewall
    - role: log2ram
    - role: docker


- name: Provision Pi-hole server
  hosts: pi3
  become: true
  vars_files:
    - group_vars/vault.yml
  roles:
    - role: common
    - role: firewall
    - role: log2ram
    - role: docker
    - role: pihole

- name: Provision backup Pi-hole server
  hosts: pi02w
  become: true
  vars_files:
    - group_vars/vault.yml
  roles:
    - role: common
    - role: firewall
    - role: log2ram
    - role: docker
    - role: pihole
