- name: Update and upgrade apt packages
  ansible.builtin.apt:
    update_cache: yes
    upgrade: dist
    autoremove: yes
    autoclean: yes

- name: Enable NetworkManager
  ansible.builtin.service:
    name: NetworkManager
    enabled: true
    state: started

- name: Disable SSH root login
  ansible.builtin.lineinfile:
    path: /etc/ssh/ssh_config
    line: 'PermitRootLogin=no'
    state: present

- name: Install common packages
  ansible.builtin.apt:
    name:
      - vim
      - curl
      - wget
      - htop
      - git
    state: present